name: maybe-finance_devcontainer

x-db-env: &db_env
  POSTGRES_USER: postgres
  POSTGRES_DB: maybe_development
  POSTGRES_PASSWORD: postgres

x-rails-env: &rails_env
  DB_HOST: db
  HOST: "0.0.0.0"
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: maybe_development
  BUNDLE_PATH: /bundle
  REDIS_URL: redis://redis:6379/1

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ..:/workspace:cached
      - bundle_cache:/bundle

    ports:
      - "3008:3000"

    command: bash -c "cd /workspace && bundle install && npm install && bundle exec rails server -b 0.0.0.0 -p 3000"

    environment:
      <<: *rails_env
      RAILS_ENV: development
      PORT: 3000

    depends_on:
      - db
      - redis

  worker:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: bash -c "cd /workspace && bundle install && bundle exec sidekiq"
    restart: unless-stopped
    volumes:
      - ..:/workspace:cached
      - bundle_cache:/bundle
    environment:
      <<: *rails_env
      RAILS_ENV: development
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis-data:/data
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - devcontainer_postgres-data:/var/lib/postgresql/data
    environment:
      <<: *db_env
    ports:
      - "5432:5432"

volumes:
  devcontainer_postgres-data:
    external: true
  redis-data:
  bundle_cache:
